import { ThemeProvider, createTheme } from "@mui/material";
import Head from "next/head";
import { HomeSection } from "../components/Section/HomeSection";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import { BottomMenu } from "../components/Navigation/BottomMenu";
import { Box } from "@mui/system";
import { NewProject } from "../components/Section/NewProject";

const theme = createTheme({
  palette: {
    blue: {
      main: "#1f78f0",
    },
    notSelected: {
      main: "#ccc",
    },
    black: {
      main: "rgb(0,0,0)",
    },
  },
});

export default function Home() {
  // const [swiper, setSwiper] = React.useState<Swiper>()

  return (
    <Box
      sx={{
        position: "relative",
        top: 0,
      }}
    >
      <ThemeProvider theme={theme}>
        <Head>
          <title>TaskCard | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Swiper
          spaceBetween={10}
          slidesPerView={1}
          initialSlide={0}
          zoom={false}
          // onSlideChange={() => console.log('slide change')}
          onSwiper={(swiper) => {
            // console.log(swiper)
            // setSwiper(swiper)
          }}
        >
          <SwiperSlide virtualIndex={1}>
            <HomeSection />
          </SwiperSlide>
          <SwiperSlide virtualIndex={2}>
            <NewProject />
          </SwiperSlide>
          <SwiperSlide virtualIndex={3}>
            <HomeSection />
          </SwiperSlide>
          <SwiperSlide virtualIndex={4}>
            <HomeSection />
          </SwiperSlide>
          <BottomMenu />
        </Swiper>
      </ThemeProvider>
    </Box>
  );
}
