import { ThemeProvider, createTheme } from '@mui/material'
import Head from 'next/head'
import { HomeSection } from '../components/Section/HomeSection'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css';
import { BottomMenu } from '../components/Navigation/BottomMenu';
import { Box } from '@mui/system';

const theme = createTheme(
  {
    palette: {
      blue: {
        main: "#1f78f0"
      },
      notSelected: {
        main: '#ccc'
      },
      black: {
        main: 'rgb(0,0,0)'
      }
    }
  }
)

export default function Home() {
  return (
    <Box
      sx={{
        position: 'relative',
        top: 0,
      }}>
      <ThemeProvider theme={theme}>
        <Head>
          <title>TaskCard | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Swiper
          spaceBetween={10}
          slidesPerView={1}
          onSlideChange={() => console.log('slide change')}
          onSwiper={(swiper) => console.log(swiper)}
        >
          <SwiperSlide>
            <HomeSection />
          </SwiperSlide>
          <SwiperSlide>
            <HomeSection />
          </SwiperSlide>
          <SwiperSlide>
            <HomeSection />
          </SwiperSlide>
          <SwiperSlide>
            <HomeSection />
          </SwiperSlide>
          <BottomMenu />
        </Swiper>
      </ThemeProvider>
    </Box>
  )
}
