import { ThemeProvider, createTheme } from '@mui/material'
import Head from 'next/head'
import {Main} from '../components/Sections/HomeSection'

const theme = createTheme(
  {
    palette: {
      blue: {
        main: "#1f78f0"
      },
      notSelected: {
        main: '#ccc'
      },
      black: {
        main: 'rgb(0,0,0)'
      }
    }
  }
)

export default function Home() {
  return (
    <div>
      <ThemeProvider theme={theme}>
      <Head>
        <title>TaskCard | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      </ThemeProvider>
    </div>
  )
}
